Traceback (most recent call last):
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/olgascrivner/anaconda3/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/olgascrivner/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gram_vectorizer.transform(X).toarray()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-20-b80cac92101f>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgram_vectorizer[0m[0;34m.[0m[0mtransform[0m[0;34m([0m[0mX[0m[0;34m)[0m[0;34m.[0m[0mtoarray[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py[0m in [0;36mtransform[0;34m(self, raw_documents)[0m
[1;32m   1248[0m [0;34m[0m[0m
[1;32m   1249[0m         [0;31m# use the same matrix-building strategy as fit_transform[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1250[0;31m         [0m_[0m[0;34m,[0m [0mX[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_count_vocab[0m[0;34m([0m[0mraw_documents[0m[0;34m,[0m [0mfixed_vocab[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1251[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0mbinary[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1252[0m             [0mX[0m[0;34m.[0m[0mdata[0m[0;34m.[0m[0mfill[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py[0m in [0;36m_count_vocab[0;34m(self, raw_documents, fixed_vocab)[0m
[1;32m   1106[0m         [0mvalues[0m [0;34m=[0m [0m_make_int_array[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1107[0m         [0mindptr[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1108[0;31m         [0;32mfor[0m [0mdoc[0m [0;32min[0m [0mraw_documents[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1109[0m             [0mfeature_counter[0m [0;34m=[0m [0;34m{[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1110[0m             [0;32mfor[0m [0mfeature[0m [0;32min[0m [0manalyze[0m[0;34m([0m[0mdoc[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'TfidfVectorizer' object is not iterable
TypeError: 'TfidfVectorizer' object is not iterable

